name: STM32 CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 1. Собираем прошивку через Docker
      # (Проверка размера уже вшита в Dockerfile! Если размер превышен, сборка упадет здесь)
      - name: Build Firmware via Docker
        run: |
          docker build --target artifacts --output type=local,dest=./build_out .

      # 2. Загрузка готовой прошивки в артефакты
      # Обрати внимание: убрали .elf, так как файл теперь называется просто UART_DRIVER
      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stm32-firmware
          path: build_out/UART_DRIVER
          retention-days: 7
