name: STM32 Firmware CI/CD with Renode

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-test-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Единый шаг: Компиляция C++, проверка размера Flash и интеграционные тесты в Renode
      - name: Build Firmware, Check Size & Run Renode Tests
        run: |
          docker build --target artifacts --output type=local,dest=./build_out .

      # Загрузка проверенной и протестированной прошивки в артефакты
      - name: Upload Verified Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stm32-firmware-verified
          path: build_out/UART_DRIVER
          retention-days: 7
